name: Mirror to Gitlab
on:
  push:
    paths:
      - src/BlazorComponent/src/Component/**
      - src/Masa.Blazor/**
      - .gitlab-ci.yml
  delete:
    paths:
      - src/BlazorComponent/src/Component/**
      - src/Masa.Blazor/**
      - .gitlab-ci.yml
  create:
    paths:
      - src/BlazorComponent/src/Component/**
      - src/Masa.Blazor/**
      - .gitlab-ci.yml
  workflow_dispatch:

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: config git
        run: git config --global http.postBuffer 524288000
      - uses: yesolutions/mirror-action@v0.5.1
        with:
          REMOTE: '${{ secrets.GITLAB_ADDER }}/cicd/masa.blazor1.git'
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}

