name: deploy-wasm-prd

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: git pull
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - run: git submodule foreach git checkout main
    - name: setting dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
          7.0.x
        include-prerelease: true
    - name: setting tools
      run: dotnet workload install wasm-tools
    - name: build
      run: dotnet build src/Masa.Blazor.NewDocs.sln
    - name: publish
      run: dotnet publish src/Docs/Masa.Docs.WebAssembly/Masa.Docs.WebAssembly.csproj -c Release
    - name: setup oss
      uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: "oss-cn-hangzhou.aliyuncs.com"
        access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
    - name: deploy oss
      run: ossutil cp -rf /home/runner/work/MASA.Blazor/MASA.Blazor/src/Docs/Masa.Docs.WebAssembly/bin/Release/net7.0/publish/wwwroot/ oss://masa-blazor-wasm-v1/
