name: deploy-wasm-prd

on:
  release:
    types: [ created ]
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: git pull
      uses: actions/checkout@v2
    - name: setting dotnet 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: setting tools
      run: dotnet workload install wasm-tools
    - name: dependencies
      run: git clone -b main https://github.com/BlazorComponent/BlazorComponent.git ./src/BlazorComponent
    - name: build
      run: dotnet build src
    - name: publish
      run: dotnet publish src/Doc/Masa.Blazor.Doc.WebAssembly/Masa.Blazor.Doc.WebAssembly.csproj
    - name: setup oss
      uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: "oss-cn-hangzhou.aliyuncs.com"
        access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
    - name: deploy oss
      run: ossutil cp -rf /home/runner/work/MASA.Blazor/MASA.Blazor/src/Doc/Masa.Blazor.Doc.WebAssembly/bin/Debug/net6.0/publish/wwwroot/ oss://masa-blazor-wasm/
